name: 1. poc
run-name: 1. poc

# on dispatch and on push to delete_orphan_instances
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  poc-job:
    runs-on: ubuntu-latest

    steps:
      - name: run echo hello world
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == true
        run: |
          echo "hello world"
      - name: run echo goodbye world
        run: |
          echo "goodbye world"
      - name: fail test
        run: exit 1
