name: 1. poc
run-name: 1. poc

# on dispatch and on push to delete_orphan_instances
on:
  pull_request:

jobs:
  poc-job:
    runs-on: ubuntu-latest

    steps:
      - name: run echo hello world
        run: |
          echo "hello world, this is a poc"
